def dispatch(task_path):
    filename = "write_output_test.md"
    description = "Generated by CanonCodex"
    with open(task_path, "r") as f:
        lines = f.readlines()
    for line in lines:
        if line.startswith("FILE:"):
            filename = line.split(":", 1)[1].strip()
        elif line.startswith("DESC:"):
            description = line.split(":", 1)[1].strip()
    content = f"## CanonCodex Task Output\n\n{description}\n\n- Source: {task_path}\n"
    output_path = f"outputs/{filename}"
    with open(output_path, "w") as f:
        f.write(content)
    print(f"✅ Output written to {output_path}")
