name: Auto Repair System

on:
  workflow_dispatch:

jobs:
  repair:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Re-run bootstrap
        run: python bootstrap.py
