name: CanonCodex Autosync

on:
  push:
    paths:
      - 'canoncodex_inbox/**'
      - 'memory_logs/**'
      - 'autosync_core/**'
      - '.github/workflows/**'

jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Trigger Render Deployment
        run: |
          curl -X POST "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
