on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  canoncodex-autorun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run CanonCodex
        run: PYTHONPATH=. python canoncodex/agent/main_loop.py
