name: CanonCodex Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  sync-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Sync
        run: python run_sync.py
      - name: Auto Commit & Push
        run: |
          git config user.name "CanonBot"
          git config user.email "canon@codex.bot"
          git add .
          git diff --cached --quiet || git commit -m "Auto-sync update"
          git push
