name: CanonCodex Autonomous Cycle

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/15 * * * *'  # every 15 minutes UTC
  workflow_dispatch:

jobs:
  canoncodex-autorun:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run CanonCodex Agent
        run: |
          PYTHONPATH=$GITHUB_WORKSPACE python3 canoncodex/agent/main_loop.py
