name: Daily Cleanup

on:
  schedule:
    - cron: '0 3 * * *'  # Runs every day at 03:00 UTC
  workflow_dispatch:      # Allow manual runs

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Run cleanup
        run: python cleanup.py
